name: actionstar
favicon: null
layout_spectrum: 0.12129037012346089
typography_spectrum: 0.28150150645524263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 0.405505912611261
  saturation: 0.9603124200366437
  rhythmicContrast: 0.8922143187373877
purpose: []
